sut:
  build: .
  command: >
    bash -c "
    git --version &&
    aws --version &&
    openssl version &&
    ssh -V &&
    tree --version &&
    jq --version &&
    zip -h &&
    unzip -h &&
    wget --version &&
    curl --version &&
    "
